# Generated by Django 5.1 on 2024-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em andamento'), ('C', 'Concluido')], default='P', max_length=1)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
